### ISSUE TITLE
soooooooooo accessible

### ISSUE THREAD

**Issue by jessica440** [fac20/week-9-bfop#23]
1000000000000000000000000% accessible!!!!! 🎉🎉👏

**Comment by hannahgooding** [comment]
Agreed - well done on the Lighthouse Audit team
![Screenshot 2020-09-11 at 10 28 16](https://user-images.githubusercontent.com/47333850/92902960-9dfa2e80-f419-11ea-9c59-62bb2ec56a89.png)

![](https://media.giphy.com/media/26uTsgxxplCBOasmc/giphy.gif)

I can tab through and use the website with my keyboard and without a mouse...
![](https://media.giphy.com/media/cAmga2A1HufwPQyB12/giphy.gif)

**Comment by hannahgooding** [comment]
Not all users use a mouse 
[](https://media.giphy.com/media/cAmga2A1HufwPQyB12/giphy.gif)

**Comment by hannahgooding** [comment]
without a mouse
[](https://media.giphy.com/media/cAmga2A1HufwPQyB12/giphy.gif)

**Comment by hannahgooding** [comment]
without a mouse
[](https://media.giphy.com/media/cAmga2A1HufwPQyB12/giphy.gif)
